name: Blake Jones - Colourist - Instructor - Consultant
favicon: null
layout_spectrum: 0.8934256683569402
typography_spectrum: 0.5131791972089559
title: Blake Jones - Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#405952'
    - '#9C9B7A'
    - '#FFD393'
    - '#FF974F'
    - '#F54F29'
  brandStrength: 0.6708735027350485
  lightness: 0.8897772745694965
  saturation: 0.746821713866666
  rhythmicContrast: 0.24555032118223608
purpose: []
