name: Blake Jones - Colourist - Instructor - Consultant
favicon: null
layout_spectrum: 0.7496989776846021
typography_spectrum: 0.21011631772853434
title: Blake Jones - Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3E454C'
    - '#2185C5'
    - '#7ECEFD'
    - '#FFF6E5'
    - '#FF7F66'
  brandStrength: 0.5509228918235749
  lightness: 0.1197962611913681
  saturation: 0.8119167424738407
  rhythmicContrast: 0.6784360895399004
purpose: []
