name: Blake Jones - Colourist - Instructor - Consultant
favicon: null
layout_spectrum: 0.25559882749803364
typography_spectrum: 0.2970575096551329
title: Blake Jones - Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.7528531523421407
  lightness: 0.7532826571259648
  saturation: 0.8570480425842106
  rhythmicContrast: 0.6457482003606856
purpose: []
