name: Blake Jones - Colourist - Instructor - Consultant
favicon: null
layout_spectrum: 0.7496989776846021
typography_spectrum: 0.04000061471015215
title: Blake Jones - Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.2852147452067584
  lightness: 0.20354431634768844
  saturation: 0.8503460448700935
  rhythmicContrast: 0.718586961273104
purpose: []
