name: Blake Jones - Colourist - Instructor - Consultant
favicon: null
layout_spectrum: 0.38815
typography_spectrum: 0.3768230329733342
title: Blake Jones - Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333132'
    - '#d5bb96'
    - '#6c92e7'
    - '#505d94'
    - '#b26946'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
