layout_spectrum: 0.16721068671904504
typography_spectrum: 0.8531860916409642
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.8801671059336513
  lightness: 0.47391461092047393
  saturation: 0.7938488393556327
  rhythmicContrast: 0.03854511631652713
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Blake Jones - Colorist - Consultant - Instructor - Author
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
description: Colourist - Consultant - Instructor - Writer
purpose: []
