name: Blake Jones - Colourist - Instructor - Consultant
favicon: null
layout_spectrum: 0.11253333347849548
typography_spectrum: 0.8502314279321581
title: Blake Jones - Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.49262448539957404
  lightness: 0.07778665889054537
  saturation: 0.40161728113889694
  rhythmicContrast: 0.07364548603072762
purpose: []
