name: Blake Jones - Colourist - Instructor - Consultant
favicon: null
layout_spectrum: 0.89065
typography_spectrum: 0.3768230329733342
title: Blake Jones - Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ccab40'
    - '#242623'
    - '#b8bab5'
    - '#6a6c69'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
