layout_spectrum: 0.7724569290876389
typography_spectrum: 0.41562889609485865
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.8212200321722776
  lightness: 0.5805612970143557
  saturation: 0.56311966618523
  rhythmicContrast: 0.03936533723026514
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Blake Jones - Colorist - Consultant - Instructor - Author
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
description: Colourist - Consultant - Instructor - Writer
purpose: []
