name: Blake Jones - Colourist - Instructor - Consultant
favicon: null
layout_spectrum: 0.43155
typography_spectrum: 0.3768230329733342
title: Blake Jones - Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060604'
    - '#333832'
    - '#8aa4b1'
    - '#916643'
    - '#5176aa'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
