name: Blake Jones - Colourist - Instructor - Consultant
favicon: null
layout_spectrum: 0.7496989776846021
typography_spectrum: 0.4056634670123458
title: Blake Jones - Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.13886582758277655
  lightness: 0.6669114450924098
  saturation: 0.2566477186046541
  rhythmicContrast: 0.3589262042660266
purpose: []
