typography_spectrum: 0.89928003330715
color:
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
  brandStrength: 0.12914352235384285
  lightness: 0.5538432616740465
  saturation: 0.6446589641273022
  rhythmicContrast: 0.2517275351565331
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7344983301591128
analytics:
  google: null
  facebook: null
  twitter: null
name: Blake Jones - Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Blake Jones
description: ''
purpose: []
