name: Blake Jones - Colourist - Instructor - Consultant
favicon: null
layout_spectrum: 0.7073849057778716
typography_spectrum: 0.2727320482954383
title: Blake Jones - Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#292929'
    - '#5B7876'
    - '#8F9E8B'
    - '#F2E6B6'
    - '#412A22'
  brandStrength: 0.3422918585129082
  lightness: 0.4764050003141165
  saturation: 0.4897758229635656
  rhythmicContrast: 0.5282490928657353
purpose: []
