layout_spectrum: 0.22251832066103816
typography_spectrum: 0.8480995860882103
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.28175944020040333
  lightness: 0.24966345052234828
  saturation: 0.24984763213433325
  rhythmicContrast: 0.817529434338212
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Blake Jones - Colorist - Consultant - Instructor - Author
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
description: Colourist - Consultant - Instructor - Writer
purpose: []
