layout_spectrum: 0.7660436404403299
typography_spectrum: 0.728718469152227
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.9239675272256136
  lightness: 0.29762163339182734
  saturation: 0.11602394189685583
  rhythmicContrast: 0.7885819438379258
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Blake Jones - Colorist - Consultant - Instructor - Author
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
description: Colourist - Consultant - Instructor - Writer
purpose: []
