name: Blake Jones - Colourist - Instructor - Consultant
favicon: null
layout_spectrum: 0.7496989776846021
typography_spectrum: 0.9341072724200785
title: Blake Jones - Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  brandStrength: 0.114791119704023
  lightness: 0.6342190601862967
  saturation: 0.9516158422920853
  rhythmicContrast: 0.7817417522892356
purpose: []
