layout_spectrum: 0.04964190465398133
typography_spectrum: 0.9670377594884485
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.48804044048301876
  lightness: 0.5751198350917548
  saturation: 0.5301731792278588
  rhythmicContrast: 0.06248855497688055
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Blake Jones - Colorist - Consultant - Instructor - Author
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
description: Colourist - Consultant - Instructor - Writer
purpose: []
