layout_spectrum: 0.15881647751666605
typography_spectrum: 0.6713579730130732
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.5960072095040232
  lightness: 0.9392413117457181
  saturation: 0.6521803275682032
  rhythmicContrast: 0.9899312804918736
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Blake Jones - Colorist - Consultant - Instructor - Author
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
description: Colourist - Consultant - Instructor - Writer
purpose: []
