name: Blake Jones - Colourist - Instructor - Consultant
favicon: null
layout_spectrum: 0.9835224840790033
typography_spectrum: 0.0004028221592307091
title: Blake Jones - Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.42361076548695564
  lightness: 0.49446889641694725
  saturation: 0.24944367981515825
  rhythmicContrast: 0.45674945460632443
purpose: []
