name: Blake Jones - Colourist - Instructor - Consultant
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3768230329733342
title: Blake Jones        Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.11520826420746744
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
