name: Blake Jones - Colourist - Instructor - Consultant
favicon: null
layout_spectrum: 0.7496989776846021
typography_spectrum: 0.22063212795183063
title: Blake Jones - Colourist - Instructor - Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.13780911499634385
  lightness: 0.6330097604077309
  saturation: 0.9486824041232467
  rhythmicContrast: 0.6840290394611657
purpose: []
